export const ProjectItems = [
    // Photo by ivan Torres on Unsplash
    {
        projectID: 1,
        projectTitle: 'ASI SOAR Game',
        description:
            'During the COVID-19 Pandemic, I created a game for Freshman to complete in liu of having an in-person Orientation. The students were asked to participate in',
        imgSrc: '../../assets/images/soar-game.png',
        url: 'https://www.asicsulb.org/soar/',
        layoutID: 'asi-soar-game',
        techStack: ['HTML', 'CSS', 'React', "API's", 'Node', 'Express', 'Git'],
    },
    {
        projectID: 2,
        projectTitle: 'Down Friend Groups',
        description: 'Down is a ',
        imgSrc: '../../assets/images/downlogo.png',
        url: 'https://www.joindown.com',
        layoutID: 'down-friend-groups',
        techStack: [
            'React Native',
            'TypeScript',
            'React.js',
            'Expo',
            'Firebase',
            'Firestore',
            'Git',
        ],
    },
    {
        projectID: 3,
        projectTitle: 'ASI CSULB and ASI Recreation',
        description: 'I have worked for ',
        imgSrc: '../../assets/images/asicsulb.png',
        url: 'https://www.asicsulb.org/corporate/',
        layoutID: 'asi-soar-game',
        techStack: [
            'HTML5',
            'CSS',
            'JavaScript',
            'Bootstrap',
            'UI/UX Design',
            'Search Engine Optimization',
            'Google Analytics',
            'PHP',
            'Content Management',
            'Git',
        ],
    },
];
